spring:
    application:
      name: sandbox
    datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    liquibase:
      change-log: classpath:liquibase-changelog.xml
    data:
      web:
        pageable:
          default-page-size: 25
          max-page-size: 100
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${MAIL_ACC}
      password: ${MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true

server:
  error:
    include-message: always
    include-binding-errors: always

app:
  uploadDir: ./data/productImages/
  cart:
    cleanup:
      expression: "0 0 3 * * *"
  email:
    sender: empty
  serviceAddress: http://localhost:4200
  payments:
    p24:
      testMode: true
      url: https://secure.przelewy24.pl
      apiUrl: https://secure.przelewy24.pl/api/v1
      merchantId: ${MERCHANT_ID}
      posId: ${POS_ID}
      urlReturn: http://railway.com/sandbox-frontend
      urlStatus: http://railway.com/sandbox-backend
      crc: ${CRC}
      secretKey: ${SECRET_KEY}

      testUrk: https://sandbox.przelewy24.pl
      testApiUrl: https://sandbox.przelewy24.pl/api/v1
      testUrlReturn: http://railway.com/sandbox-frontend
      testUrlStatus: http://railway.com/sandbox-backend
      testCrc: ${TEST_CRC}
      testSecretKey: ${TEST_SECRET_KEY}

logging:
  level:
    org:
      springframework:
        web: info
        security: info

jwt:
  expireTime: ${EXPIRE_TIME}
  secret: ${JWT_SECRET}

