spring:
    application:
      name: sandbox
    datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    liquibase:
      change-log: classpath:liquibase-changelog.xml
    data:
      web:
        pageable:
          default-page-size: 25
          max-page-size: 100