spring:
    application:
      name: sandbox
    datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    liquibase:
      change-log: classpath:liquibase-changelog.xml
    data:
      web:
        pageable:
          default-page-size: 25
          max-page-size: 100
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${MAIL_ACC}
      password: ${MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true

server:
  error:
    include-message: always
    include-binding-errors: always

app:
  uploadDir: ./data/productImages/
  cart:
    cleanup:
      expression: "0 0 3 * * *"

  email:
    sender: empty